In [2]:
import pandas as pd

In [14]:
def concat_data(app_name: str) -> pd.DataFrame:
    # Load the uploaded CSV files
    file_path_apple = f'result/{app_name}/{app_name}.csv'
    file_path_google = f'result/{app_name}/{app_name}_GooglePlayStore.csv'

    # Reading the CSV files
    apple_data = pd.read_csv(file_path_apple)
    google_data = pd.read_csv(file_path_google)

    # Step 1: Rename columns to make them consistent across both datasets
    apple_data_renamed = apple_data.rename(columns={"rating": "score", "review": "content"})

    # Step 2: Dropping 'title' column from the Apple dataset for consistency
    apple_data_cleaned = apple_data_renamed.drop(columns=["Unnamed: 0", "title"])

    # Dropping 'Unnamed: 0' column from the Google dataset for consistency
    google_data_cleaned = google_data.drop(columns=["Unnamed: 0"])

    # Step 3: Merge the datasets
    combined_data = pd.concat([apple_data_cleaned, google_data_cleaned], ignore_index=True)

    combined_data.to_csv(f'{app_name}_combined.csv')

    return combined_data

In [7]:
data = pd.read_csv('result/duoswim/duoswim.csv')
data = data.rename(columns={'rating': 'score', 'review': 'content'})
data = data.drop(columns=["Unnamed: 0", "title"])
data.to_csv('duoswim_combined.csv')
data

                                              content  score
0   Fantastic app, it changed my way to workout in...      5
1   Finally a swim app that looks great and provid...      5
2   Positive: The coaching side seems ok and decen...      2
3   This app is very easy to use. I love how you c...      5
4   Perfect app. Used to love swimming but hadn‚Äôt ...      5
5   After trying a few apps for my swimming, the D...      5
6   This is the first app I have found where I can...      5
7   Very nice app not so complicated as others. I ...      5
8   This app was exactly what I needed to start tr...      5
9   I currently swim 2-3 times a week and this app...      5
10  This app is quality, helping me build up my sw...      5
11  I am so impressed with the variety of programs...      5
12  I am an experienced swimmer and this app has s...      5
13  Perfect app for me to start my training journe...      5
14  Awesome app, great training schemes and graphi...      5

In [15]:
combined_data = concat_data('form-swim')
combined_data

                                               content  score
0    I like sport gadgets, but usually 9 out of 10 ...      5
1    My biggest question was if I was going to be a...      5
2    This has been a game changer in how I swim. Fi...      5
3    The googles are fine and the workout generatio...      3
4    This and bone conduction headphones have me sw...      5
..                                                 ...    ...
205                                 Awesome technology      5
206                                 Awesome possum üèä üëì      5
207                                            Amazing      5
208                                    Fitness swimmer      5
209  Saya mimpi Mengintai tirai kamar Amira Kota Ki...      5

[210 rows x 2 columns]

In [16]:
combined_data = concat_data('myswimpro')
combined_data

                                               content  score
0    Got the app 5 weeks ago and I have made more p...      4
1    I am not a compet√≠os swimmer but I enjoy it an...      5
2    Very impressed.  As a long time swimmer with a...      5
3    Let‚Äôs be honest, for many of us, our best comp...      5
4    First and foremost SwimPro is a great app with...      4
..                                                 ...    ...
938                            Everything requires pro      3
939                           Gooodddddd‚úåÔ∏è‚ù§Ô∏èüí´üòá‚ù§Ô∏è‚úåÔ∏èüí´‚ù§Ô∏èüòá      5
940                                               ÿπÿßŸÑ€å      5
941                                         Works well      5
942                                                NaN      5

[943 rows x 2 columns]

In [17]:
combined_data = concat_data('swim-com')
combined_data

                                               content  score
0    After using this app for two years on a Pebble...      4
1    Strictly from an App Design standpoint, it bre...      3
2    They‚Äôve made some good improvements to the app...      4
3    At 70 yo I sometimes ( no, all the time) need ...      5
4    This app has all the potential of being great ...      2
..                                                 ...    ...
639                                               Nice      5
640                                             Useful      5
641                                               Best      5
642                                         Code brown      1
643                                          I like it      5

[644 rows x 2 columns]

In [18]:
combined_data = concat_data('swimup')
combined_data

                                              content  score
0   Amazing app, amazing coach and superb courses....      5
1   Tried a few training apps for getting into swi...      5
2   I have been trying to learn how to freestyle w...      4
3   Great app! Simple as it is, works good for beg...      5
4   They put me on 2 levels before champion but th...      2
..                                                ...    ...
61  –°–ø–∞—Å–∏–±–æ, –ø—Ä–∏–ª–æ–∂–µ–Ω–∏–µ–º –≥–µ–Ω–µ—Ä–∏—Ä—É–µ—Ç –∏–Ω—Ç–µ—Ä–µ—Å–Ω—ã–µ —Ç—Ä–µ...      4
62  –°–ø–∞—Å–∏–±–æ, –æ—Ç–ª–∏—á–Ω–æ–µ –ø—Ä–∏–ª–æ–∂–µ–Ω–∏–µ –¥–ª—è —Ç—Ä–µ–Ω–∏—Ä–æ–≤–æ–∫. –ü...      5
63                                           Nice app      5
64                                          Very good      5
65                                           Paid app      3

[66 rows x 2 columns]